# Generated by Django 5.0.3 on 2024-03-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='letstalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Full_Name', models.CharField(max_length=250)),
                ('TextArea', models.TextField()),
            ],
        ),
    ]
