# Generated by Django 5.1.5 on 2025-07-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='letstalk',
        ),
    ]
